config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'no-bullshit'     => 'pages#no_bullshit'
  get 'no-monetizing'   => 'pages#no_monetizing'
  get 'no-surveillance' => 'pages#no_surveillance'
  get 'timeline'        => 'pages#timeline'

  get 'register'  => 'users#new'
  post 'register' => 'users#create'

  get 'login'  => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  resources :users, only: [:show, :update]
  resources :tweets, only: [:create, :destroy]

  post 'follow/:user_id'     => 'followers#create',  as: :follow
  delete 'unfollow/:user_id' => 'followers#destroy', as: :unfollow

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :follower,  class_name: 'User', counter_cache: :following_count
  belongs_to :following, class_name: 'User', counter_cache: :followers_count
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :author, class_name: 'User', counter_cache: true

  validates :content, presence: true, length: { within: 1..140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true

  validates :email, presence: true, uniqueness: true

  has_many :tweets

  has_many :passive_relationships, class_name: 'Follower', foreign_key: 'following_id'
  has_many :followers, class_name: 'User', through: :passive_relationships

  has_many :active_relationships, class_name: 'Follower', foreign_key: 'follower_id'
  has_many :following, class_name: 'User', through: :active_relationships

  def timeline_tweets
    @timeline_tweets ||= Tweet.where(author_id: timeline_author_ids).
      order(created_at: :desc)
  end

  private

  def timeline_author_ids
    @timeline_author_ids ||= [id] +
      active_relationships.to_a.map(&:following_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: 'Not authorized' if current_user.nil?
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authorize

  # POST /follow/1
  def create
    current_user.active_relationships.create(following_id: params[:user_id])
    redirect_to user_url(params[:user_id])
  end

  # DELETE /unfollow/1
  def destroy
    current_user.active_relationships.where(following_id: params[:user_id]).destroy_all
    redirect_to user_url(params[:user_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authorize, except: [:home, :no_bullshit, :no_monetizing, :no_surveillance]

  def home
    redirect_to timeline_url if current_user
  end

  def no_bullshit
  end

  def no_monetizing
  end

  def no_surveillance
  end

  def timeline
    # Initialize a tweet for the "What's happening?" form
    @tweet = Tweet.new

    # Retrieve the list of tweets (posted, retweeted, followed)
    @timeline_tweets = current_user.timeline_tweets
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /login
  def new
  end

  # POST /login
  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  # DELETE /logout
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authorize

  before_action :set_tweet, only: [:destroy]

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params).tap do |t|
      t.author = current_user
    end

    if @tweet.save
      redirect_to timeline_url
    else
      redirect_to timeline_url, alert: @tweet.errors.full_messages
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to timeline_url, notice: 'Tweet was successfully deleted.'
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users/1
  def show
    @tweets = Tweet.where(author: @user).order(created_at: :desc)
  end

  # GET /register
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_following?(user_id)
    current_user.active_relationships.to_set.map(&:following_id).include?(user_id)
  end
end

app/views/layouts/_current_user.html.erb
<div class="user-infos">
  <%= link_to 'Home', root_path %> |
  <% if current_user %>
    Logged in as <%= current_user.username %> |
    <%= link_to 'Logout', logout_path %>
  <% else %>
    Want to join?
    <%= link_to 'Log in', login_path %> or
    <%= link_to 'sign up', register_path %> in seconds.
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Twitter</title>
  <meta name="description" content="Online social networking service.">
  <meta name="author" content="Mickael Pham">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <%= favicon_link_tag %>

  <!-- JavaScript
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- CSRF
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/current_user' %>

    <%= render 'layouts/messages' %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="home-welcome">
  <h1>Your social network, private.</h1>

  <%= link_to 'Register now', register_path, class: 'button button-primary' %>

  <div class="row values">
    <div class="one-third column">
      <h4>No bullshit</h4>

      <p>
        We are not here to fool you, this social network is
        <%= link_to 'yours', no_bullshit_path %>.
      </p>
    </div>

    <div class="one-third column">
      <h4>No monetizing</h4>

      <p>
        We do not make money with your
        <%= link_to 'personal information', no_monetizing_path %>,
        period.
      </p>
    </div>

    <div class="one-third column">
      <h4>No surveillance</h4>

      <p>
        Everything is <%= link_to 'encrypted', no_surveillance_path %>, with a
        <%= link_to 'distributed', no_surveillance_path %> architecture.
      </p>
    </div>
  </div>
</div>

app/views/pages/timeline.html.erb
<div class="row timeline-content">
  <div class="four columns profile">
    <div class="timeline-profile">
      <h5>
        <%= current_user.username %>

        <small>@<%= current_user.username %></small>
      </h5>

      <table class="u-full-width">
        <thead>
          <tr>
            <th>Tweets</th>
            <th>Following</th>
            <th>Followers</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td><%= current_user.tweets_count %></td>
            <td><%= current_user.following_count %></td>
            <td><%= current_user.followers_count %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="timeline-trends">
      <h5>Global Trends</h5>
    </div>
  </div>

  <div class="eight columns">
    <%= form_for @tweet do |f| %>
      <%= f.text_area :content, class: 'u-full-width', placeholder: 'What\'s happening?' %>
      <%= f.submit 'Tweet', class: 'button-primary' %>
    <% end %>

    <h4>While you were away&#8230;</h4>

    <% if @timeline_tweets.any? %>
      <% @timeline_tweets.each do |t| %>
        <div class="timeline-tweet">
          <div class="timeline-tweet-meta"></div>

          <div class="timeline-tweet-header">
            <strong class="timeline-tweet-author">
              <%= link_to t.author.username, user_path(t.author) %>
            </strong>
            @<%= t.author.username %> &bullet;
            <%= t.updated_at %>
          </div>

          <div class="timeline-tweet-content">
            <%= t.content %>
          </div>

          <div class="timeline-tweet-footer">
            <ul>
              <li><a href="#">reply</a></li>
              <li><a href="#">retweet</a></li>
              <% if t.author == current_user %>
                <li><%= link_to 'delete', t, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>It seems like there is nothing to display here :(</p>
    <% end %>
</div>

app/views/users/new.html.erb
<%= form_for @user, url: register_path, html: { class: 'register-form' } do |f| %>
  <div class="row">
    <div class="one-third column">
      <% if @user.errors.any? %>
        <h5>Form is invalid</h5>

        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'u-full-width', placeholder: 'how you introduce yourself', autofocus: true %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'u-full-width', placeholder: 'won\'t be shared' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'u-full-width', placeholder: 'the longer the better' %>

      <%= f.submit 'Register now', class: 'button-primary' %>
    </div>

    <div class="two-thirds column">
      <h2>Welcome to Twitter.</h2>

      <p>
        Connect with your friends — and other fascinating people. Get
        in-the-moment updates on the things that interest you. And watch events
        unfold, in real time, from every angle.
      </p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row user-profile">
  <div class="four columns">
    <% if current_user == @user %>
      <h5>My Profile</h5>
    <% else %>
      <h5><%= @user.username %>'s profile</h5>
    <% end %>

    <table class="u-full-width profile-stats">
      <thead>
        <tr>
          <th>Tweets</th>
          <th>Following</th>
          <th>Followers</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= @user.tweets_count %></td>
          <td><%= @user.following_count %></td>
          <td><%= @user.followers_count %></td>
        </tr>
      </tbody>
    </table>

    <% if current_user == @user %>
      <button>Edit Profile</button>
    <% elsif is_following?(@user.id) %>
      <%= link_to 'Unfollow', unfollow_path(@user.id), method: :delete, class: 'button' %>
    <% else %>
      <%= link_to 'Follow', follow_path(@user.id), method: :post, class: 'button button-primary' %>
    <% end %>
  </div>

  <div class="eight columns">
    <% if current_user == @user %>
      <h5>My Tweets</h5>
    <% else %>
      <h5><%= @user.username %>'s Tweets</h5>
    <% end %>

    <% if @tweets.any? %>
      <% @tweets.each do |t| %>
        <div class="timeline-tweet">
          <div class="timeline-tweet-meta"></div>

          <div class="timeline-tweet-header">
            <strong class="timeline-tweet-author">
              <%= link_to t.author.username, user_path(t.author) %>
            </strong>
            @<%= t.author.username %> &bullet;
            <%= t.updated_at %>
          </div>

          <div class="timeline-tweet-content">
            <%= t.content %>
          </div>

          <div class="timeline-tweet-footer">
            <ul>
              <li><a href="#">reply</a></li>
              <li><a href="#">retweet</a></li>
              <% if t.author == current_user %>
                <li><%= link_to 'delete', t, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>It seems like there is nothing to display here :(</p>
    <% end %>
  </div>
</div>